### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jcalonso** [wunzeco/ansible-elasticsearch-curator#7]
HI  @wunzeco!
Would it be possible to tag a new release from master, there are some changes on master related to `iteritems` that I'm facing when running this role on python 3.

I hope its possible, thanks!

**Comment by wunzeco** [comment]
Hi @jcalonso 

I welcome any improvements. If you could raise a PR with your changes please.

**Comment by jcalonso** [comment]
Thanks @wunzeco, the actual fix is already on master:
https://github.com/wunzeco/ansible-elasticsearch-curator/commit/7d714bf2d2b3204ab3103731b70239a359fcee04

I was just wondering if you could do tag a release so that I can lock my playbook to an aspecific version instead of having to set `master` as the version.

Let me know if Im not clear :)
Thanks

**Comment by wunzeco** [comment]
https://github.com/wunzeco/ansible-elasticsearch-curator/tree/v1.2

**Comment by jcalonso** [comment]
Sweet, cheers mate!
